const container = document.getElementById("container");

const images = document.querySelectorAll("div.image:not(.empty)");
const titles = [
    "굳은 날개 ", 
    "좁은 길", 
    "낡은 생각", 
    "집 속 꿈", 
    "두통", 
    "두 가지 미래", 
    "온전한 지도는 주어지지 않는다", 
    "언어의 획득과 상실", 
    "떠났던 곳으로 돌아가고 있는지도 모른 채", 
    "오늘의 바깥", 
    "도중", 
    "구애의 달리기", 
    "꿈의 스타일", 
    "일곱 개의 소제목", 
    "습관의 적", 
    "착란, 아마도 우연하지 않은", 
    "타고난 심장", 
    "악몽을 뒤로 하고 ", 
    "구멍, 그 다음은", 
    "꿈에서 본 길", 
    "기다림", 
    "눈가리개", 
    "주문", 
    "천천히", 
    "raw material", 
    "이야기의 압력", 
    "몸 밖에서 하는 생각", 
    "밀어내는 말", 
    "시작된 시간", 
    "결국은 하나의 길", 
    "내가 가진 것 ", 
    "버거운 새벽", 
    "꿈의 잔상", 
    "다프네 (대상이 되지 않기 위해)", 
    "세상과 세상", 
    "타이밍의 문제", 
    "작지만 확실한 전쟁 ", 
    "밤에만 자라는 나무들", 
    "정교한 가면일수록", 
    "자유로운 삶", 
    "욕구의 제한 시간", 
    "잊혀진 출발지와 도착지", 
    "움직이려는", 
    "not yet", 
    "아름다움이 없는 곳", 
    "커다란 마음 속에서", 
    "헤어짐의 흔적", 
    "셔터", 
    "아무것도 잃어버린 것 없이", 
    "정리되지 않을 이야기의 조각들", 
    "얼음 속에서 일어나는 일", 
    "아직 없는 것 또는 원래 있었던 것", 
    "왜곡, 미끄러지는 진심", 
    "별나무", 
    "소리 없는 곳", 
    "날씨가 좋아지면 빛날까", 
    "행복에의 편견들", 
    "돌아갈 장소", 
    "시간과 시간, 그림", 
    "바란 적 없는 아름다움", 
    "그림과 그림자의 자국", 
    "결계 만들기", 
    "직물", 
    "어둠 속에서 더 잘 보였던", 
    "평평해진 이야기", 
    "별들에게 길이 생기고 있다면", 
    "초록색 기운", 
    "차원", 
    "어릴 때", 
    "해명해야 하는 시간", 
    "말 아래 묻혀버린", 
    "먼 앞은 볼 수 없어도", 
    "시간이 만져진다면", 
    "모이지 않는 소리", 
    "산타가 필요해", 
    "저마다의 계절 속에서", 
    "마땅히 있어야 할 장애물", 
    "불편하고 밝은 곳", 
    "이데아", 
    "동화를 잊어버리는 순간", 
    "어려운 기억", 
    "가려고 했던 곳과 반대쪽으로 가고 있는지도 몰라", 
    "아는 새, 아는 바다", 
    "균형을 위한 상상", 
    "순서가 사라진다", 
    "꺼내지 않은 기억의 테", 
    "의지는 보이지 않는 곳에 모습을 감춘다", 
    "잃어버린 인사말", 
    "들리지 않는 이유는 듣지 않기 때문이야", 
    "자리 없는 감정들", 
    "내일", 
    "과거에는 답이 없다", 
    "밤에 피는 꽃", 
    "잡아먹히지 않고", 
    "살아남은 것과 죽은 것이 뒤섞여 있다", 
    "당신이 원할 때", 
    "전쟁이 끝난 줄도 모르고", 
    "모든 과거의 방식이 튕겨져 나온다", 
    "색(色)을 찾아", 
    "마음밭에서 마음 찾기", 
    "나름의 층위", 
    "좌표", 
    "나뉘어져 있었던 세계가", 
    "얕은 눈", 
    "아직 오지 않은 사람과", 
    "여러 사람의 땅이 모여", 
    "환상은 우리를 어디로 데려갈까", 
    "옷이 충분히 가볍지 않아서", 
    "길을 네가 그려줘", 
    "부자연스러움", 
    "눈물의 기원", 
    "부드러움을 모아서", 
    "갖고 싶은 것", 
    "멀미 속에 머무르기", 
    "집 없는 사람의 집", 
    "프리즘", 
    "잊어버린 방", 
    "그림이 된 과거", 
    "어떤 색(色)도 정착하지 않고", 
    "고장난 나침반", 
    "고통과 말", 
    "반복", 
    "슬픔에게 필요한 공간", 
    "당신들이 건넨 비눗방울이", 
    "너를 보는 방식", 
    "허기", 
    "구체적인 길", 
    "당신이 딛고 있는 환상은", 
    "작고 길고 확실한 통로", 
    "경직된 기억의 방", 
    "아프지 않은 꿈", 
    "주인공", 
    "빛으로 눈 가리기", 
    "물과 빛이 모자란 섬", 
    "다른 나라로의 기회", 
    "내가 만난 사람들", 
    "꽃의 계획", 
    "기다리는 새 심장", 
    "하나씩 무너져 내린다", 
    "너를 위해 준비된 환상이 아니었으므로", 
    "나뭇잎을 뒤집으면", 
    "공허한 미래를 모아", 
    "암호", 
    "분열", 
    "잊어 놓은 감각들", 
    "당신들의 방식", 
    "온기", 
    "사라진 선물", 
    "방메 뜬 슬픔들을 모아 모아 모아서", 
    "남아 있는 끈", 
    "에로스의 휴식", 
    "네가 있었던 자리를 ", 
    "도중에 핀 꽃", 
    "외로움", 
    "땅도 하늘도 아닌 곳에", 
    "너는 사라지고", 
    "밝은 밤", 
    "바다의 모방", 
    "사진첩, 사실은 텅 비어 있었던 너", 
    "카드놀이, 상상할 수 있는 것과 없는 것 중에서", 
    "동료", 
    "희미한 내 목소리를", 
    "결과 없는 사랑들은 생각을 지어낸다", 
    "나오지 않을지도 모르는 소식을 기다려", 
    "말하지 않은 것", 
    "검은 설탕", 
    "태우거나 피우거나", 
    "말", 
    "바깥이 안 되면 안쪽으로", 
    "가짜 연결과 진짜 연결", 
    "부피 없는 성", 
    "경험", 
    "힘", 
    "시끄러움 속 시선", 
    "인공 빛", 
    "호흡", 
    "타임머신", 
    "몸 없는 단어들의 산", 
    "바다를 꿈꾸기 위해 사막을 찾는 습관", 
    "시간을 잠시 멈춰 놓고", 
    "이야기의 뒷면", 
    "생각과 너 사이를 가로막는 연결", 
    "쓰지 않은 마법", 
    "이미 있는 장소는 꿈꾸지 않는다", 
    "소원의 무게", 
    "여유의 모습", 
    "여전히 나누고 싶은 것", 
    "향기를 가로막는", 
    "딱 한 잔의 미래", 
    "우리가 살던 세상과 우리", 
    "좋아하는 맛", 
    "부푼 잠", 
    "시간이 닿지 않는 곳에 보관", 
    "준비", 
    "기억의 비", 
    "글자 또는 그림", 
    "시간으로 태우다", 
    "흉터로 그리는 지도", 
    "한 사람의 중력", 
    "상상의 시간", 
    "내일을 만드는 공장", 
    "허공에 만든 자리", 
    "시간 안에 그림이 될 수 있을까", 
    "약속에 가까이", 
    "기분(氣分)", 
    "일찍 핀 꽃", 
    "시간이 없는 곳을 떠다니는 말", 
    "지나온 길의 흔적", 
    "작은 나라", 
    "소리를 기다림", 
    "물건과 주인", 
    "두 개의 행성", 
    "만질 수 없는", 
    "누구의 손", 
    "직접 만든 캔버스", 
    "겨울에 걸친 아이", 
    "너와 나의 거리", 
    "가진 것은 열쇠와 별", 
    "보고 싶지 않아", 
    "밝은 날", 
    "액체가 되기 전에", 
    "대화", 
    "다른 나라", 
    "잠으로 꿈을 잊고 (imitation drawing _ 마티스 <Femme endormie>)", 
    "빛으로 떠난 사람 (imitation drawing _ 마티스 <Studio under the Eaves>)", 
    "그려지는 사람의 근황 (imitation drawing _ 마티스 <The Painting Lesson>)", 
    "잊은 것이 쌓이는 곳 (imitation drawing _ 마티스 <My room in Ajaccio>)", 
    "다시 이데아", 
    "혼자만의 달 ", 
    "날아오르는 방법", 
    "속에 ", 
    "멀고 확실한 곳", 
    "일인용", 
    "단계", 
    "계절, 계절, 계절,", 
    "낮잠", 
    "레몬 폭포", 
    "input & output", 
    "reaction", 
    "태어나려는 이름들", 
    "휴식", 
    "연기(緣起)", 
    "세 갈래 길과 소중했던 잎사귀들", 
    "찾아야 할 답", 
    "네가 찾는 건 여기에 없어", 
    "꼭", 
    "밟지 않고 걷기", 
    "하늘과 땅", 
    "다른 열매들은", 
    "함께 맡은 향기", 
    "수영", 
    "롤리팝", 
    "오늘", 
    "보일락 말락", 
    "모빌", 
    "비누방울", 
    "아이스크림", 
    "라임오렌지", 
    "아침길", 
    "같은 아픔", 
    "brand new", 
    "between coins", 
    "self greeting", 
    "glass apple", 
    "5 doors", 
    "heartbeat", 
    "시간과 거울", 
    "Ruler", 
    "국경, 강, 보이지 않는 바다", 
    "hint of revolution", 
    "asymmetric", 
    "back ground music", 
    "deep deep deep", 
    "커피와 책", 
    "줄다리기", 
    "사이", 
    "liquid luck", 
    "things", 
    "Im not yours please go back to your dream", 
    "얼음, 바다, 목욕", 
    "미완성", 
    "비 오는 방", 
    "새로 나온 꿈", 
    "연습", 
    "연습2", 
    "hello, fear", 
    "필요한 한 스푼", 
    "꿈 없는 잠", 
    "하늘을 잡고", 
    "오늘 모은 내일", 
    "눈에 보이는 향기", 
    "당신들의 여행", 
    "시든 사랑을", 
    "touch", 
    "my own clock", 
    "바깥의 시간에 기대어", 
    "달빛과 물을 먹고 자라고 있어", 
    "토요일", 
    "주인 잃은 물건들", 
    "길이 모여서 (day1)", 
    "길이 모여서 (day2)", 
    "길이 모여서 (day3)", 
    "길이 모여서 (day4)", 
    "길이 모여서 (day5)", 
    "길이 모여서 (day6)", 
    "꿈의 가장자리 (day1)", 
    "꿈의 가장자리 (day2)", 
    "꿈의 가장자리 (day3)", 
    "꿈의 가장자리 (day4)", 
    "꿈의 가장자리 (day5)", 
    "습관이 된 꿈 조각 (day1)", 
    "습관이 된 꿈 조각 (day2)", 
    "오래된 목적지 (day1)", 
    "습관이 된 꿈 조각 (day3)", 
    "습관이 된 꿈 조각 (day4)", 
    "습관이 된 꿈 조각 (day5)", 
    "습관이 된 꿈 조각 (day6)", 
    "습관이 된 꿈 조각 (day7)", 
    "오래된 목적지 (day2)", 
    "오래된 목적지 (day3)", 
    "오래된 목적지 (day4)", 
    "오래된 목적지 (day5)", 
    "오래된 목적지 (day6)", 
    "오래된 목적지 (day7)", 
    "오래된 목적지 (day8)", 
    "오래된 목적지 (day9)", 
    "onepiece", 
    "그리움의 말", 
    "나의 전부가 너의 조각", 
    "계절의 반대 방향", 
    "어둠", 
    "위태로운 볕", 
    "사라진 꿈들의 주인", 
    "네가 기다리는 동안 너를 기다리는 ", 
    "열매의 사연", 
    "생각하는 집 (day1)", 
    "생각하는 집 (day2)", 
    "생각하는 집 (day3)", 
    "생각하는 집 (day4)", 
    "생각하는 집 (day5)", 
    "생각하는 집 (day6)", 
    "생각하는 집 (day7)", 
    "생각하는 집 (day8)", 
    "생각하는 집 (day9)", 
    "생각하는 집 (day10)", 
    "생각하는 집 (day11)", 
    "생각하는 집 (day12)", 
    "약속 없던 날 (day1)", 
    "약속 없던 날 (day2)", 
    "약속 없던 날 (day3)", 
    "약속 없던 날 (day4)", 
    "약속 없던 날 (day5)", 
    "약속 없던 날 (day6)", 
    "약속 없던 날 (day7)", 
    "약속 없던 날 (day8)", 
    "약속 없던 날 (day9)", 
    "약속 없던 날 (day10)", 
    "약속 없던 날 (day11)", 
    "약속 없던 날 (day12)", 
    "아침보다 전", 
    "무지개 땅", 
    "모래", 
    "자국", 
    "무렵", 
    "기대", 
    "인공적인 강", 
    "멀어졌으므로", 
    "산책", 
    "결정", 
    "질서", 
    "화산", 
    "네가 불러낸 기억", 
    "낮꿈", 
    "꿈을 묻히고", 
    "좋아하는 맛으로", 
    "지금의 음", 
    "가짜 별", 
    "차오르는", 
    "세 개의 시간", 
    "투명한 목적지", 
    "미지근한 새벽", 
    "뿌리 없이", 
    "걸음마다", 
    "두 개의 중력과 하나의 빛", 
    "너의 상상 속으로", 
    "소리와 소리 없음", 
    "silent party", 
    "끝은 사람", 
    "기다리는 욕심", 
    "이동", 
    "하늘에 내린 뿌리", 
    "부자유", 
    "남쪽의 초록 (day1)", 
    "남쪽의 초록 (day2)", 
    "남쪽의 초록 (day3)", 
    "남쪽의 초록 (day4)", 
    "남쪽의 초록 (day5)", 
    "남쪽의 초록 (day6)", 
    "남쪽의 초록 (day7)", 
    "남쪽의 초록 (day8)", 
    "남쪽의 초록 (day9)", 
    "남쪽의 초록 (day10)", 
    "남쪽의 초록 (day11)", 
    "남쪽의 초록 (day12)", 
    "남쪽의 초록 (day13)", 
    "남쪽의 초록 (day14)", 
    "남쪽의 초록 (day15)", 
    "언어로 만들어진 다리", 
    "꽃 품은 빙산에 도착", 
    "달 띄우기", 
    "꼭대기에서 하는 일", 
    "엉겨붙은 옛날과 함께", 
    "계속 계속 남는 것", 
    "그때 했던 대화", 
    "눈물 위에 올린 집", 
    "네가 모르는 약속들", 
    "모여든 조각들", 
    "착지 또 착지", 
    "데려다줘서 고마워", 
    "먼 섬과 기다리는 배 (day1)", 
    "먼 섬과 기다리는 배 (day2)", 
    "먼 섬과 기다리는 배 (day3)", 
    "먼 섬과 기다리는 배 (day4)", 
    "먼 섬과 기다리는 배 (day5)", 
    "먼 섬과 기다리는 배 (day6)", 
    "먼 섬과 기다리는 배 (day7)", 
    "먼 섬과 기다리는 배 (day8)", 
    "먼 섬과 기다리는 배 (day9)", 
    "먼 섬과 기다리는 배 (day10)", 
    "먼 섬과 기다리는 배 (day11)", 
    "먼 섬과 기다리는 배 (day12)", 
    "먼 섬과 기다리는 배 (day13)", 
    "먼 섬과 기다리는 배 (day14)", 
    "먼 섬과 기다리는 배 (day15)", 
    "untitled", 
    "untitled", 
    "untitled", 
    "untitled", 
    "untitled", 
    "늙은 나무와 모르는 너 ", 
    "지하에서 자라는 ", 
    "네가 닫아놓은 문, 잊어버린 시", 
    "untitled", 
    "선의 감각", 
    "untitled", 
    "헤어진 모습 그대로 ", 
    "untitled", 
    "untitled", 
    "titling", 
    "untitled", 
    "untitled", 
    "untitled", 
    "untitled", 
    "untitled", 
    "untitled", 
    "untitled", 
    "untitled", 
    "untitled", 
    "untitled", 
    "untitled", 
    "untitled", 
    "untitled", 
    "untitled", 
    "untitled", 
    "windowpicturemirror", 
    "untitled", 
    "untitled", 
    "untitled", 
    "untitled", 
    "towards", 
    "obstacles", 
    "untitled", 
    "untitled", 
    "물 흐르는 방향 따라 (day1)", 
    "물 흐르는 방향 따라 (day2)", 
    "물 흐르는 방향 따라 (day3)", 
    "물 흐르는 방향 따라 (day4)", 
    "물 흐르는 방향 따라 (day5)", 
    "물 흐르는 방향 따라 (day6)", 
    "물 흐르는 방향 따라 (day7)", 
    "물 흐르는 방향 따라 (day8)", 
    "물 흐르는 방향 따라 (day9)", 
    "물 흐르는 방향 따라 (day10)", 
    "물 흐르는 방향 따라 (day11)", 
    "물 흐르는 방향 따라 (day12)", 
    "물 흐르는 방향 따라 (day13)", 
    "물 흐르는 방향 따라 (day14)", 
    "물 흐르는 방향 따라 (day15)", 
    "물 흐르는 방향 따라 (day16)", 
    "물 흐르는 방향 따라 (day17)", 
    "물 흐르는 방향 따라 (day18)", 
    "물 흐르는 방향 따라 (day19)", 
    "제자리로 오르기", 
    "호흡의 색", 
    "글을 보는 눈", 
    "이별 후", 
    "그 행성", 
    "조용한 색만 터졌으면 좋겠어", 
    "이제 꽃은 유리 밖에서도 살아", 
    "몸들", 
    "보이지 않는 소리는 듣지 않아", 
    "잡념을 모아", 
    "쓴 적 없는 사람", 
    "흘러올 시간은 여기에", 
    "도망가는 주제", 
    "겹치다 보면 통로가 생길 거야", 
    "바깥 아래", 
    "untitled", 
    "새기기엔 이른 ", 
    "something big", 
    "untitled", 
    "질문 없는 곳으로 ", 
    "소년의 말", 
    "your moon", 
    "and your thought", 
    "old dream", 
    "this is you", 
    "instead", 
    "lost energy", 
    "hey empty door", 
    "아름다움이 엉겨붙으면", 
    "이것은 재료가 아니고", 
    "너의 공허", 
    "무엇이 더 소중해", 
    "못생긴 꿈들", 
    "너의 시간은 무슨 색이었어", 
    "환상은 없어", 
    "지도는 여전히 움직이고 있을까", 
    "untitled", 
    "몸이 만들어지다 멈추었어", 
    "밖은 아직", 
    "잘게 부서지는 내일 ", 
    "많이 알고 싶지 않아", 
    "시작하는 달 ", 
    "멀리 멀리 ", 
    "마음을 떼어다가 붙일 수 있었으면 좋겠어", 
    "flake", 
    "shape of spring", 
    "white imitation", 
    "고여 있던 것들이 노래가 되러 ", 
    "마음 만한 집들", 
    "years ago (day1)", 
    "years ago (day2)", 
    "years ago (day3)", 
    "years ago (day4)", 
    "years ago (day5)", 
    "years ago (day6)", 
    "years ago (day7)", 
    "through____", 
    "years ago (day8)", 
    "years ago (day9)", 
    "years ago (day10)", 
    "years ago (day11)", 
    "years ago (day12)", 
    "years ago (day13)", 
    "도착한 사람", 
    "years ago (day14)", 
    "years ago (day15)", 
    "years ago (day16)", 
    "years ago (day17)", 
    "쓸모없는 재능", 
    "years ago (day18)", 
    "where is the sun", 
    "years ago (day19)", 
    "years ago (day20)", 
    "years ago (day21)", 
    "years ago (day22)", 
    "untitled", 
    "stupid dreams", 
    "ugly attention", 
    "사랑이 없는 곳에서 태어난 사람을 ", 
    "주인공을 죽이러", 
    "cant touch", 
    "최대한 작고 얇게", 
    "벽과 날개", 
    "no one", 
    "from above", 
    "거짓말을 하고 있는 쪽은", 
    "이번 궤적", 
    "얕은 비밀들", 
    "열매는 나중에", 
    "꽃과 병이 따로 ", 
    "daily face", 
    "stay here", 
    "마음줄", 
    "untitled (day1)", 
    "바라보는 중", 
    "거울", 
    "몰래 피는 꽃", 
    "pray or burn", 
    "untitled (day2)", 
    "지난 꿈 위에서 다음 꿈", 
    "side", 
    "포기가 빚어지면", 
    "가만히 있어도 ", 
    "가까운 별부터 ", 
    "그림자와 함께", 
    "느끼는 것보다 조금 더 가까이 ", 
    "여전히 갖고 싶어", 
    "untitled (day3)", 
    "잠깐, 숫자만 사는 곳으로 ", 
    "규칙", 
    "the face doesn't say about anything", 
    "뒤쳐진 언덕에서", 
    "꿈을 등지면", 
    "untitled", 
    "untitled (day4)", 
    "limit", 
    "untitled", 
    "left n right", 
    "you should love your dawn", 
    "weird place", 
    "u don’t need me", 
    "갇힌 빛", 
    "may be not real ", 
    "네가 사는 작은 방", 
    "your fake years", 
    "the other hand", 
    "untitled", 
    "가장 개인적인 것들", 
    "behind your thought", 
    "자른 꿈 사이로 ", 
    "I'm not a destination", 
    "모자란 만큼", 
    "시간의 감각을 기억해 내 ", 
    "Berlin Home Café (day1)", 
    "untitled ", 
    "untitled", 
    "Berlin Home Café (day2)", 
    "Berlin Home Café (day3)", 
    "Berlin Home Café (day4)", 
    "Berlin Home Café (day5)", 
    "Berlin Home Café (day6)", 
    "Berlin Home Café (day7)", 
    "Berlin Home Café (day8)", 
    "Berlin Home Café (day9)", 
    "Berlin Home Café (day10)", 
    "Berlin Home Café (day11)", 
    "Berlin Home Café (day12)", 
    "from window", 
    "혼자 피는 꽃은 없어", 
    "towards, simplistic", 
    "towards, simplistic 2", 
    "without answer", 
    "hide your beauty here", 
    "small dream", 
    "나가지 못하는 아이들", 
];

let currentImage;
let imageIndex;

let currentRect;
let divLeft;
let divTop;
let divWidth;

images.forEach((image, i) => {
    image.addEventListener("mouseenter", function() {
        //마우스 올린 날짜 박스의 위치와 가로 길이 측정 
        currentImage = image;
        imageIndex = i;
        currentRect = currentImage.getBoundingClientRect();
        divLeft = currentRect.left;
        divTop = currentRect.top;
        divWidth = currentRect.width;
        
        //새로운 제목 추가 
        imageTitle = document.createElement("div");
        imageTitle.classList.add("imagetitle");

        imageTitle.textContent = `${titles[i]}`;
        imageTitle.style.position = "absolute";
        imageTitle.style.left = `${divLeft + divWidth}px`;
        imageTitle.style.top = `${divTop}px`;

        imageTitle.style.backgroundColor = "#555";
        imageTitle.style.height = `${currentRect.height}px`;
        imageTitle.style.padding = "0 10px 0 10px";
        imageTitle.style.color = "#f0f0f0";
        imageTitle.style.font = `normal normal 400 0.8rem/${currentRect.height}px "Gothic A1"`;
        imageTitle.style.zIndex = 5;
        container.appendChild(imageTitle);
    });
    image.addEventListener("mouseleave", function() {
        container.removeChild(imageTitle);
    })
});

